version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    commit-message:
      prefix: "Deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "github/*"
    ignore:
      - dependency-name: "greenbone/actions"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "Deps"
