name: Build and test Python package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check and lint python packages
        uses: greenbone/actions/lint-python@v3
        with:
          package-manager: uv
          packages: gvmtools tests
          python-version: ${{ matrix.python-version }}
          linter: ruff check --diff
          formatter: ruff format --check --diff

  lint-scripts:
    name: Lint all scripts
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: greenbone/actions/uv@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync
      - name: Install additional script dependencies
        run: uv pip install -r scripts/requirements.txt
      - name: Check formatting of scripts
        run: uv run ruff format --check --diff scripts/*.gmp.py
      - name: Lint scripts
        run: |
          uv run ruff check --config scripts/ruff.toml scripts/*.py

  test:
    name: Unit tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: greenbone/actions/uv@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit test
        run: |
          uv run python -m unittest -v

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          package-manager: uv

  build-docs:
    name: Build the documentation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: greenbone/actions/uv@v3
      - name: Build docs
        run: |
          cd docs && uv run make html
