name: Conventional Commits

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: read

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Report Conventional Commits
        uses: greenbone/actions/conventional-commits@a1883bd24d2d921426b3f06413e84606ecd43bdd # v3.27.11
