name: Conventional Commits

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: read

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Report Conventional Commits
        uses: greenbone/actions/conventional-commits@554e2bc6a0e1ad94b45997a322eadf0cd350baad # v3.27.14
