name: Deploy on PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/gvm-tools/
    steps:
      - name: Build and publish to PyPI
        uses: greenbone/actions/pypi-upload@554e2bc6a0e1ad94b45997a322eadf0cd350baad # v3.27.14
