name: SBOM upload
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  SBOM-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: 'SBOM upload'
        uses: greenbone/actions/sbom-upload@f0c8b8268b98d09237774489fefc2c0ab77703aa # v3.27.13
