name: SBOM upload
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  SBOM-upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: 'SBOM upload'
        uses: greenbone/actions/sbom-upload@e31766d258c8642dc090244b8334be5b2109833d # v3.27.23
